my_string=input()
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string[-1:])
print(my_string[:1])
uno=('съешь меня, если сможешь')
uno = uno.replace(" ", "")
print(uno)
